// Generated by https://quicktype.io

export interface IResumeFormat {
    headerConfig: HeaderConfig;
    panels:       Panel[];
    sidePanel:    SidePanel[];
}

export interface HeaderConfig {
    name:    string;
    title:   string;
    options: HeaderConfigOption[];
}

export interface HeaderConfigOption {
    name:   string;
    icon:   string;
    href?:  string;
    value?: string;
}

export interface Panel {
    title: string;
    exps?: Exp[];
    adds?: Add[];
}

export interface Add {
    title: string;
    data:  string[];
}

export interface Exp {
    role:   string;
    date:   DateClass;
    lists?: string[];
}

export interface DateClass {
    from:     string;
    to:       string;
    at:       string;
    atIcon:   string;
    fromIcon: string;
}

export interface SidePanel {
    title:   string;
    options: SidePanelOption[];
}

export interface SidePanelOption {
    class?: string;
    text:   string;
    head?:  string;
}
